name: Test for bayesopt

on:
  push:
  pull_request:

jobs:
  tests_physbo_interface:
    name: Run tests for physbo_interface
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        os: [ubuntu-22.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install pytest
      - name: Install bayesoptpy  # install local pkg
        run: |
          pip install .
      - name: Run pytest
        run: pytest -v tests/test_physbo_interface.py

  # for old ubuntu (20.04)
  tests_physbo_interface_ubuntu_old:
    name: Run tests for physbo_interface_ubuntu_old
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.8', '3.9']
        os: [ubuntu:20.04]
    steps:
      - name: Install system deps (for Python builds)
        run: |
          export DEBIAN_FRONTEND=noninteractive
          #apt-get update
          #apt-get install -y software-properties-common build-essential curl git
          #add-apt-repository ppa:deadsnakes/ppa -y
          apt-get update
          apt-get install -y --no-install-recommends python${{ matrix.python-version }} python3-pip

          # Use the selected python
          ln -sf /usr/bin/python${{ matrix.python-version }} /usr/local/bin/python
          ln -sf /usr/bin/pip3 /usr/local/bin/pip

          python --version
          pip --version

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install pytest
      - name: Install bayesoptpy  # install local pkg
        run: |
          pip install .
      - name: Run pytest
        run: pytest -v tests/test_physbo_interface.py

  # combo only works with python2
  tests_combo_interface:
    name: Run tests for combo_interface
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container_image:
          - ubuntu:20.04
          - python:2.7.18-buster
    container:
        image: ${{ matrix.container_image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install pytest cython numpy
      - name: Install combo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/tsudalab/combo.git
          cd combo
          python setup.py install
      - name: Install bayesoptpy  # install local pkg
        run: |
          pip install .
      - name: Run pytest
        run: |
          pytest -v tests/test_combo_interface.py
